### ISSUE TITLE
replace shared_preferences with something suitable for sensitive data

### ISSUE THREAD

**Issue by jossef** [jossef/requests#1]
shared_preferences is not the best practice for storing sensitive data. use something else

**Comment by RickStanley** [comment]
I would recomend [Flutter Secure Storage](https://github.com/mogol/flutter_secure_storage) for this, though the downside would be:  wrapper for emulating and injecting for Android and iOs for tests and other things.

**Comment by jossef** [comment]
@RickStanley thanks. Would you like to PR this change?

**Comment by jet10000** [comment]
https://github.com/tekartik/sembast.dart/blob/master/sembast/README.md

**Comment by hereabdulla** [comment]
will this helps?? 
https://pub.dev/packages/encrypted_shared_preferences

**Comment by ianmaciel** [comment]
> I would recomend [Flutter Secure Storage](https://github.com/mogol/flutter_secure_storage) for this, though the downside would be: wrapper for emulating and injecting for Android and iOs for tests and other things.

There is a downside: Flutter Secure Storage works only on Android iOS and Linux. Windows, macOS and Web won't be supported.

**Comment by sehnryr** [comment]
Hive is cross-platform and has strong encryption built in.

Closing because #58 fixes this issue and implements hive via stash_hive.

**Comment by LightIn-death** [comment]
Look like storing sensitive data in cookie is mainly a bad practice.
I think if the devs would like to store sensitive data, it's not a "requests" issue.
