### ISSUE TITLE
Creating a JSON from POST request data

### ISSUE THREAD

**Issue by genesiscz** [jossef/requests#2]
Hello.

I've been struggling with this for a while and couldn't figure it out. When I use your package like this 
```dart
Requests.post("https://phpcode.eu/test.php", body: {"username": "test", "password": "test"})
    .then((value) { print(value); });
```
I am having problems with getting the data with a simple PHP script
```php
<?php
print_r($_POST);
```

It probably does not recognize the POST data in JSON format and prints an empty array. The same goes for `$_REQUEST`.

However if I replace this line in src/requests.dart
```dart
        future = client.post(uri, body: bodyString, headers: headers);
```
with
```dart
        future = client.post(uri, body: body, headers: headers);
```
and comment out 
```dart
contentTypeHeader = "application/json";
```
it properly gives me the data sent
```php
Array
(
    [username] => test
    [password] => test
)
```

What am I missing or doing wrong?
Thanks for the support, this has been an amazing package!

**Comment by jossef** [comment]
Thanks for reporting, will update soon

**Comment by jossef** [comment]
I've tested your example (and url) you posted. You are reading the posted json wrong in your php code. 

instead of this:

```php
<?php
print_r($_POST);
?>
```

use this:

```php
<?php
$inputJSON = file_get_contents('php://input');
print_r($inputJSON);
?>
```
https://stackoverflow.com/a/7084677/3191896

-----

confirmed using Postman

before:
![image](https://user-images.githubusercontent.com/1287098/52877225-14617c80-3162-11e9-8719-13c5e589fef3.png)

after:
![image](https://user-images.githubusercontent.com/1287098/52877463-b84b2800-3162-11e9-826c-3b98f9d5c7a2.png)

**Comment by genesiscz** [comment]
I know that you can read it from stdin, but it is not a standard way to read a POST data. It makes more sense to post it as a Form instead of a JSON.

**Comment by jossef** [comment]
I'm confused. your original question is about JSON.
If you are suggesting to support `multipart/form-data` I would appreciate a Pull Request  :)

**Comment by genesiscz** [comment]
I mean, why would you want to send it as a raw JSON by default and not inherit the behavior of `http` package? It makes more sense for me that the post function corresponds to the PHP's $_POST variable, as well as `http` package's post function. I think it makes more sense because, as of `http` package documentation,

```
  /// [body] sets the body of the request. It can be a [String], a [List<int>]
  /// or a [Map<String, String>]. If it's a String, it's encoded using
  /// [encoding] and used as the body of the request. The content-type of the
  /// request will default to "text/plain".
  ///
 /// If [body] is a List, it's used as a list of bytes for the body of the
  /// request.
  ///
  /// If [body] is a Map, it's encoded as form fields using [encoding]. The
  /// content-type of the request will be set to
  /// `"application/x-www-form-urlencoded"`; this cannot be overridden.
```

Doesn't it make absolutely more sense to just inherit the behaviour instead of malforming it?

**Comment by jossef** [comment]
You are correct, this should be supported.

Since this issue's title & description is misleading (you referred JSON) - I've opened a new issue regarding supporting this. https://github.com/jossef/requests/issues/4

I would appreciate a PR
