### ISSUE TITLE
Cookie not follow ignore set correctly

### ISSUE THREAD

**Issue by eggate** [jossef/requests#23]
https://github.com/jossef/requests/blob/70728614cd11069a5cf8f1c9092b6885ada5f3b3/lib/src/requests.dart#L92

variable "cookie" in this line should be variable "one" and also you should apply ignore characters case on ignores set

**Comment by jossef** [comment]
@eggate, thanks!
can you submit a PR?

**Comment by jossef** [comment]
Merged and released requests 3.1.0
thanks!
