### ISSUE TITLE
query params typing

### ISSUE THREAD

**Issue by mirrari0** [jossef/requests#27]
Currently, the methods accept Map<String, dynamic> for query params however the uri.replace() method requires that to be Map<String,String>. 

Not sure which is preferable but either Requests could own converting to the query params to a Map<String, String> returning some kind exception to the user if the query params can't be mapped or the api could be updated to require a Map<String, String> for the queryParams.

Makes the users life much easier

for example: 

```dart
await Requests.get('https://google.com', queryParameters: {'id': '1', 'name': 123});
```

will raise a runtime exception of

> type 'int' is not a subtype of type 'Iterable<dynamic>'

**Comment by jossef** [comment]
Thanks!
IMO, for better DX, the string conversion should be done inside in case someone delivers a number value.
`Map<String, dynamic>` + inner conversion to `Map<String, String>`. Can you please submit a PR?

**Comment by lohanidamodar** [comment]
Hi, I like the work you guys have done. II
@mirrari0 @jossef If nobody is working I would like to get on this? Any suggestions.
Thank you

**Comment by jossef** [comment]
https://stackoverflow.com/q/61975389/3191896

adding a fix

**Comment by xxorathaa** [comment]
i'm not 100% sure, but it looks like this change (or unfortunately something between 3.1.0 and 3.3.0) somehow broke being able to pass query parameters as a list:

eg
Map<String, dynamic> queryParams = {
  keyOne: "valueOne",
  keyTwo: "valueTwo",
  keyThree: [valueThree, valueFour, valueFive]
};

feel free to tell me i'm wrong as i haven't been able to get my call working even if i change it to Map<String, dynamic> queryParams = {
  keyOne: "valueOne",
  keyTwo: "valueTwo",
  keyThree: "valueThree&keyThree=valueFour&keyThree=valueFive"
};
