### ISSUE TITLE
add flutter web support 

### ISSUE THREAD

**Issue by teknolojia** [jossef/requests#31]

**Comment by jossef** [comment]
Currently no.
Would you like to submit a PR to add flutter web support?

**Comment by ianmaciel** [comment]
What is missing for web support?

**Comment by sehnryr** [comment]
As said in https://api.dart.dev/stable/2.16.1/dart-io/dart-io-library.html, the dart:io library is not supported on web apps.
> **Important:** Browser-based apps can't use this library. Only the following can import and use the dart:io library:
> - Servers
> - Command-line scripts
> - Flutter mobile apps
> - Flutter desktop apps

And since it a dependency of requests we cannot do much but wait until the dart team allows it.
