### ISSUE TITLE
Drop flutter dependency ?

### ISSUE THREAD

**Issue by giuliano-oliveira** [jossef/requests#37]
I really like this library, it really does http requests easy, like in python,  but i think it's unnecessary having a flutter dependency.

I would like to use this package in an another package that i am working on, but i don't want it to have a flutter dependency, since this new package doesn't have any UI manipulation or some Android/IOS exclusive functionality.

So, my suggestion is to somehow drop the flutter,logging and shared_preferences dependence, so that the above situation doesn't happen with another developer, improving this package usability.

**Comment by jossef** [comment]
@llpinokio 
this package was originally designed for flutter

I can see why a regular dart package makes sense.
thanks for the suggestion, may split this repo into two

**Comment by mingsai** [comment]
It'd be great if the package is compatible everywhere that Dart runs. Not quite sure about the dependency effort vs compatibility. I think this has been one of the more successful packages for HTTP and would love to use it on Mac/Windows/Linux/iOS/Android and whatever comes next.

**Comment by ianmaciel** [comment]
> I really like this library, it really does http requests easy, like in python, but i think it's unnecessary having a flutter dependency.
> 
> I would like to use this package in an another package that i am working on, but i don't want it to have a flutter dependency, since this new package doesn't have any UI manipulation or some Android/IOS exclusive functionality.
> 
> So, my suggestion is to somehow drop the flutter,logging and shared_preferences dependence, so that the above situation doesn't happen with another developer, improving this package usability.

I was think about the same... 

I think it is possible to instead of removing those libraries (and forking this repo), pass the instance (SharedPreferences) when constructing the class.

**Comment by jossef** [comment]
@ianmaciel great suggestion

**Comment by ianmaciel** [comment]
This could also solve #1.

The trade-off would be a more complex setup.

Instead of:
```
var r = await Requests.get('https://google.com');
r.raiseForStatus();
String body = r.content();
```

Would be necessary create a logger and storage.
```
Requests requests = Resquests(SharedPreferences(), Logger());
var r = await Requests.get('https://google.com');
r.raiseForStatus();
String body = r.content();
```

Do you think it worth?
I might be possible to "avoid" loggin/saving if null.

I still thinking how to do that in Flutter. I've already done something similar with android aar/jar to make it platform independent, but never in Dart.

**Comment by sehnryr** [comment]
My suggestion would be to replace shared_preferences with hive, which don't have flutter dependency. I think that will also solve #1.
However, I don't know how the logger could be replaced. But @ianmaciel suggestion to pass a nullable instance of the logger could solve the issue.

**Comment by sehnryr** [comment]
☝️ Here is my PR for that. I've used stash_hive which is more easy to handle that hive directly.

Also, I don't know why I thought that the logger was an issue, so I just ignored it. Now on my fork it all works well without relying on flutter.

The PR doesn't involve new features, so the update will be seamless. Now we just need to wait until it is merged.

**Comment by giuliano-oliveira** [comment]
Closing because #58 fixes it.
