### ISSUE TITLE
no longer handling list of strings as a single queryParam

### ISSUE THREAD

**Issue by xxorathaa** [jossef/requests#38]
i'm not 100% sure, but it looks like something between 3.1.0 and 3.3.0 somehow broke being able to pass query parameters as a list:

eg
Map<String, dynamic> queryParams = {
keyOne: "valueOne",
keyTwo: "valueTwo",
keyThree: [valueThree, valueFour, valueFive]
};

feel free to tell me i'm wrong as i haven't been able to get my call working even if i change it to Map<String, dynamic> queryParams = {
keyOne: "valueOne",
keyTwo: "valueTwo",
keyThree: "valueThree&keyThree=valueFour&keyThree=valueFive"
};

**Comment by jossef** [comment]
hey
this is related to the change.
can you please give an example of how this should be done in the final url?

**Comment by xxorathaa** [comment]
so passing in this map as queryParams:
Map<String, dynamic> queryParams = {
keyOne: "valueOne",
keyTwo: "valueTwo",
keyThree: [valueThree, valueFour, valueFive]
};

i expect my url to be:
https://subdomain.domain.com/path?keyOne=valueOne&keyTwo=valueTwo&keyThree=valueThree&keyThree=valueFour&keyThree=valueFive

**Comment by baskar007** [comment]
Any update on the issue ?

**Comment by jossef** [comment]
planning to add support
@baskar007, do you have time to fix this and submit a PR?

**Comment by baskar007** [comment]
Sure.. let me chk.

**Comment by baskar007** [comment]
Hi @jossef Pull Request #43 submitted.
