### ISSUE TITLE
Dependencies updates

### ISSUE THREAD

**Issue by tlkops** [jossef/requests#52]
Hello,

Following Flutter 2.0 update, Firebase now depends on http 0.13.0 which conflicts with requests on 0.12.0. Could you please update the dependencies to match more recent packages?
I'm happy to put together a PR.

**Comment by ashishbeck** [comment]
There are more conflicts actually. It would be really good if all the packages that it depends on could be updated. I have had conflicts with http, logging and crypto

**Comment by ashishbeck** [comment]
> Hello,
> 
> Following Flutter 2.0 update, Firebase now depends on http 0.13.0 which conflicts with requests on 0.12.0. Could you please update the dependencies to match more recent packages?
> I'm happy to put together a PR.

There are more conflicts actually. It would be really good if all the packages that it depends on could be updated. I have had conflicts with http, logging and crypto. Are you interested in creating a fork with all the updates? Let me know if you have time or need help.

**Comment by tlkops** [comment]
Yes ok, I'll put together a PR with dep updates.

**Comment by tlkops** [comment]
PR Available #53

**Comment by ashishbeck** [comment]
It works great. Thanks!
I hope the dev merges it soon

**Comment by Binozo** [comment]
Still not merged

**Comment by briankariuki** [comment]
Updates still not available on pub.dev

**Comment by rktvsiim** [comment]
Bump.
Thanks for the great package! Would be great to see the dependencies update published to pub.dev

**Comment by stedekay** [comment]
I wanted to test this library for my project but I am not able to install it because of dependency issues. As far as I can see the updates are already merged into master but it needs a new version tagged and published.
Is it possible to make a new version available on pub.dev? Would be really great.

**Comment by akash66agarwal** [comment]
> I wanted to test this library for my project but I am not able to install it because of dependency issues. As far as I can see the updates are already merged into master but it needs a new version tagged and published. Is it possible to make a new version available on pub.dev? Would be really great.

Me also looking for the same as well, there are conflicts with other packages.

**Comment by christiancodes** [comment]
Running into this as well.

**Comment by sehnryr** [comment]
Closing because update 4.1.0 is now available on pub.dev
