### ISSUE TITLE
failed to install null safety version

### ISSUE THREAD

**Issue by carlhung** [jossef/requests#59]
i added the null safety in the yaml.
`requests: ^4.0.0-nullsafety.0`

but I got this error:
`Because note depends on requests ^4.0.0-nullsafety.0 which doesn't match any versions, version solving failed.`

**Comment by sehnryr** [comment]
requests has been updated to 4.1.0 on pub.dev. You can now update your pubspec.yaml with :
```yaml
dependencies:
  requests: ^4.1.0
```

I'm closing the issue since the issue was resolved.
