### ISSUE TITLE
SSL handshake error on self-signed cert

### ISSUE THREAD

**Issue by Ali-Azmoud** [jossef/requests#7]
Hi
Can you provide an example of Self Sign Certification request.
I want to request to a `https` website, but get following error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (18567): 	CERTIFICATE_VERIFY_FAILED: certificate is not yet valid(handshake.cc:352))
```

**Comment by jossef** [comment]
@Ali-Azmoud thanks for reporting

need to add a parameter to allow requests without verifying the SSL certificate
can you submit a PR?

**Comment by jossef** [comment]
added flag `verify:false`

```
      var r = await Requests.get('https://expired.badssl.com/', verify: false);
      r.raiseForStatus();
```
