### ISSUE TITLE
Flutter Web not working (HttpClient not found)

### ISSUE THREAD

**Issue by LDprg** [jossef/requests#71]
**Describe the bug**
I use your Libary for request/login to my backend. On Windows Desktop and Android everything works fine, but as soon as I want to build my app for Web I get the error shown below. 

I tried to use `import 'package:universal_io/io.dart';` for fixing it, but That only fixes the HttpClient error not the IOClient.

Please fix!

**Error**
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
/C:/Users/LD/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/requests-4.3.0/lib/src/requests.dart:244:22: Error: Method not found: 'HttpClient'.
      var ioClient = HttpClient();
                     ^^^^^^^^^^
/C:/Users/LD/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/requests-4.3.0/lib/src/requests.dart:246:16: Error: Method not found: 'IOClient'.
      client = IOClient(ioClient);
               ^^^^^^^^
Failed to compile application.
```

**To Reproduce**
1. Build App with "Chrome(web)" device (Flutter)

**Expected behavior**
No errors and working build

**Desktop**
 - Browser (Chrome & Edge) on WIndows

**Comment by sehnryr** [comment]
It seems like I did not make a great job at adding web support for requests. To get into the details, it's the bad certificate handling that causes this issue. I am currently trying to make it work, but I tried dio and universal_io but couldn't get it running without encountering this issue.

It is still urgent though, but I am overloaded with work so I can't really get into fixing this issue for now. If you find a fix, please open a PR.

**Comment by sehnryr** [comment]
I've merged your changes on the conditional imports, but I think it would be nice to have the web support shown on pub.dev. I'll try to find a way to do that, but in the meantime we will have to make do with this.
