### ISSUE TITLE
setstoredcookies using cookiejar

### ISSUE THREAD

**Issue by rizkyputrapb** [jossef/requests#74]
Hey, there's an issue when I follow the example of storing cookies. In the example, the parameter of _setStoredCookies(String hostname, Map<String, String> cookies)_. But when I try to follow it, the parameter is _setStoredCookies(String hostname, CookieJar cookies)_. Did I use a different version of the library or the example is not updated yet? Thanks!

![image](https://user-images.githubusercontent.com/43906521/172146230-bb7116c3-ce55-4c67-8c1f-06b73f07a6c0.png)

**Comment by sehnryr** [comment]
Hi! Since 4.3.0 where I changed the structure of the stored cookies, but I just forgot to make the change to the example in the readme... My bad. I've now updated the readme!

In summary, in 4.3.0, to manually store the cookies, you should do:
```dart
var cookies = CookieJar.parseCookiesString("session=bla");
await Requests.setStoredCookies(hostname, cookies);
```

**Comment by sehnryr** [comment]
Also, one way finding out how to do things, is to look at the test file https://github.com/jossef/requests/blob/f8a668f21ff8636f432937c94bda09bcf09d20d7/test/requests_test.dart
