### ISSUE TITLE
create function to manually add cookies

### ISSUE THREAD

**Issue by xxorathaa** [jossef/requests#76]
in the past we could add cookies via:

```dart
Future<void> addCookieToRequests(String name, String value) async {
  final Map<String, String> savedCookies = await Requests.getStoredCookies(Requests.getHostname(serviceUrl));
  savedCookies[name] = value;
  await Requests.setStoredCookies(Requests.getHostname(serviceUrl), savedCookies);
}
```

now the working solution is more complex:

```dart
// ignore: implementation_imports
import 'package:requests/src/cookie.dart';
...
Future<void> addCookieToRequests(String name, String value) async {
  final CookieJar cookieJar = await Requests.getStoredCookies(Requests.getHostname(serviceUrl));
  cookieJar.delegate[name] = Cookie(name, value);
  await Requests.setStoredCookies(Requests.getHostname(serviceUrl), cookieJar);
}
```

if instead Requests exposed a function to add cookies this could be simplified to something like:
Requests.addCookie(String url, String name, dynamic value);

in this way we would not have any need to expose the cookies.dart file as well as having a clean handling of cookies.

**Comment by sehnryr** [comment]
Hi, I think it would be better like that too. As I have integrated cookie handling with `CookieJar`, I didn't really thought about the drawbacks.

I'll add this feature right away!

**Comment by xxorathaa** [comment]
@sehnryr appreciate the speed on this one. i tried it out and had some difficulties. after tinkering for a minute i found that i need to still call a different Requests function
```dart
      String serviceUrl = 'www.domain.com'
      await Requests.addCookie(Requests.getHostname(serviceUrl), name, value);
```
as opposed to:
```dart
      String serviceUrl = 'www.domain.com'
      await Requests.addCookie(serviceUrl, name, value);
```
obviously calling getHostname(serviceUrl) works, but was this intended? do you think there could be value in having both one that takes a url as a human readable string and allows Requests to call getHostname() internally in addition to what you have already added?

**Comment by sehnryr** [comment]
To be honest with you, I just thought of making it similar to the other methods. But now that you mention it, I think it would be better if the other methods could also take the url instead of the hostname.

**Comment by xxorathaa** [comment]
cool, will keep my eyes on the changelog! i'm in no rush for it considering we have a way to make it work already, but i appreciate your getting back to me and the attention your giving to this issue.

**Comment by sehnryr** [comment]
@xxorathaa I've opened #78, do you think there should be more to add?

**Comment by xxorathaa** [comment]
personally, i would add new methods vs changing the original ones. if you
were to add new ones woth the same name but String url in the signature,
the new functions can accomplish the gethostname() functionality then call
the original ones. this allows additional functionality, both types of
usability, and no breaking changes.

but thats just my two cents, and im not sure how much complexity adding the
new functions would add to the maintainability of the repo.
