### ISSUE TITLE
CookieJar is not exposed

### ISSUE THREAD

**Issue by juvs** [jossef/requests#79]
If you use Requests.getStoredCookies() it return a Future CookieJar, but CookieJar is not exposed.

```
library requests;

export 'src/requests.dart';
export 'src/response.dart';
export 'src/cookie.dart';
```

As a workaround we need to import the specify source, but we get a warning from Dart.

![image](https://user-images.githubusercontent.com/204912/188227154-7f41d85d-37d4-4473-8a34-b7bec29b14d2.png)

**Comment by sehnryr** [comment]
https://github.com/jossef/requests/blob/master/lib/src/cookie.dart is now exposed with 7d3d30924a81c755b9d086db6fb6b38192f80ed5.

I'll make a release right away.
