### ISSUE TITLE
Requests on localhost with custom port won'work

### ISSUE THREAD

**Issue by durduliu2009** [jossef/requests#8]
Hello, 
If I make a request on `await Requests.get("http://localhost:1337/pois", json: true);` the request will fail 
`Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 51113`
I mention that on that url localhost:1337/pois there is a service that is working and return me a json payload so it's clear that this won't be the problem.

I see in error log attached that port is 51113 can somehow set it custom ?  
Can somehow overcome this ? 
Many thanks in advance

**Comment by jossef** [comment]
it's something with your environment (server app closed or incorrect network interface)
tested on my endpoint with `localhost:1337` via python's simple http server

![image](https://user-images.githubusercontent.com/1287098/67145808-32512500-f28d-11e9-882c-c20209cd78d4.png)


```dart
await Requests.get('http://localhost:1337/');
```

as you can see, it handles custom ports
also adding to unit tests a test request to `http://portquiz.net:8080/`

**Comment by jossef** [comment]
@durduliu2009 did you ran this on an emulator?
