### ISSUE TITLE
[URGENT] 4.6.0 breaks building mobile-only apps

### ISSUE THREAD

**Issue by imdatsolak** [jossef/requests#81]
**Describe the bug**
Please check my comment on your last commit.

4.6.0 breaks building for mobile only platforms by unconditionally importing `browser_client.dart`, which is available **only on web**

**To Reproduce**
1. Create a mobile-only app
2. Add `requests`
3. import requests in `main.dart`
4. Try compiling

**Expected behavior**
Compile

**Desktop (please complete the following information):**
 - OS: iOS / Android

**Smartphone (please complete the following information):**
- N/A

**Additional context**
- Please use conditional import

**Comment by imdatsolak** [comment]
Line 4 of src/requests.dart:
import 'package:http/http.dart';
    if (dart.library.html) 'package:http/browser_client.dart'
    if (dart.library.io) 'package:http/io_client.dart';

**Comment by sehnryr** [comment]
> Line 4 of src/requests.dart:
> 
> ```dart
> import 'package:http/http.dart'
>     if (dart.library.html) 'package:http/browser_client.dart'
>     if (dart.library.io) 'package:http/io_client.dart';
> ```

This would overwrite the import of `http/http.dart`.
The easy fix would be to do:
```

**Comment by sehnryr** [comment]
While I try to fix the issue, I've retracted the release from pub.dev.

**Comment by imdatsolak** [comment]
Thanks a million...

**Comment by sehnryr** [comment]
I hope the 4.7.0 will not break anything. I've tested it on android, linux and web so it should be ok.
